### ISSUE TITLE
Merge Member Profiles

### ISSUE THREAD

**Issue by bapril** [tridentli/pitchfork#39]
Simple way to merge user profiles.

Suggest:

new button for "merge accounts" in user profile. The form has 2 sections. "Merge into another account" and "Accept Merge". Descriptive text explains that you first login to the account that will be lost and perform the "Merge into another account" process. This will set recover_token to "RECOVER:$sha256($nonce)" and presents the nonce to the user.

The user then logs into the "gaining account" and goes to "Accept merge" where they enter the username and nonce of the "losing account".

If the nonce matches, begin the merge process per existing code.

**Comment by bapril** [comment]
CLI version exists, this is the UI enhancement. 

user merge <new> <old>

**Comment by bapril** [comment]
This mostly exists. Currently it can't handle the case when both members share a TG. (panics). 

or: pq: duplicate key value violates unique constraint "member_trustgroup_pkey"
goroutine 126 [running]:
runtime/debug.Stack(0x16, 0xc420052230, 0x4e)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
trident.li/pitchfork/lib.(*PfDB).exec(0x19e5cc0, 0x19a8c20, 0xc42048e480, 0x1012901, 0xffffffffffffffff, 0x16af116, 0x35, 0xc420456ca0, 0x2, 0x2, ...)
	/usr/local/go/src/trident.li/pitchfork/lib/db.go:675 +0x825
trident.li/pitchfork/lib.(*PfDB).execA(0x19e5cc0, 0x19a8c20, 0xc42048e480, 0x169f80b, 0x1c, 0xffffffffffffffff, 0x16af116, 0x35, 0xc420456ca0, 0x2, ...)
	/usr/local/go/src/trident.li/pitchfork/lib/db.go:738 +0xb1
trident.li/pitchfork/lib.(*PfDB).Exec(0x19e5cc0, 0x19a8c20, 0xc42048e480, 0x169f80b, 0x1c, 0xffffffffffffffff, 0x16af116, 0x35, 0xc420456ca0, 0x2, ...)
	/usr/local/go/src/trident.li/pitchfork/lib/db.go:779 +0xba
trident.li/pitchfork/lib.User_merge(0x19a8c20, 0xc42048e480, 0xc42048d794, 0xa, 0xc42048d79f, 0xb, 0x0, 0x0, 0x15b8fc0, 0xc420674e88)
	/usr/local/go/src/trident.li/pitchfork/lib/user.go:863 +0x873
trident.li/pitchfork/lib.user_merge(0x19a8c20, 0xc42048e480, 0xc420064700, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/trident.li/pitchfork/lib/user.go:928 +0x10a
trident.li/pitchfork/lib.(*PfCtxS).Menu(0xc42048e480, 0xc4200646f0, 0x3, 0x3, 0xc42009a480, 0xd, 0xd, 0xa, 0xa)
	/usr/local/go/src/trident.li/pitchfork/lib/menu.go:230 +0xe6a
trident.li/pitchfork/lib.user_menu(0x19a8c20, 0xc42048e480, 0xc4200646f0, 0x3, 0x3, 0x0, 0x0)
	/usr/local/go/src/trident.li/pitchfork/lib/user.go:1236 +0x5f9
trident.li/pitchfork/lib.(*PfCtxS).Menu(0xc42048e480, 0xc4200646e0, 0x4, 0x4, 0xc420012c60, 0x4, 0x4, 0xc42018e6f0, 0xd)
	/usr/local/go/src/trident.li/pitchfork/lib/menu.go:230 +0xe6a
trident.li/pitchfork/lib.(*PfCtxS).Cmd(0xc42048e480, 0xc4200646e0, 0x4, 0x4, 0xc420230687, 0x186)
	/usr/local/go/src/trident.li/pitchfork/lib/menu.go:256 +0x8f
trident.li/pitchfork/ui.(*PfUIS).Cmd(0xc420247380, 0xc4200646e0, 0x4, 0x4, 0x0, 0x0)
	<autogenerated>:1 +0x5a
trident.li/pitchfork/ui.h_api(0x19af6e0, 0xc420247380)
	/usr/local/go/src/trident.li/pitchfork/ui/cmd.go:17 +0x71
trident.li/pitchfork/ui.(*PfUIS).MenuPath(0xc420247380, 0xc4200d9800, 0xe, 0x1c, 0xc4202473a0)
	/usr/local/go/src/trident.li/pitchfork/ui/menu.go:247 +0x3b2
trident.li/pitchfork/ui.(*PfUIS).UIMenu(0xc420247380, 0xc420174000, 0xd, 0xd)
	/usr/local/go/src/trident.li/pitchfork/ui/menu.go:264 +0xaa
trident.li/pitchfork/ui.(*PfRootUIS).H_root(0xc420457160, 0x199d840, 0xc420414000, 0xc420459800)
	/usr/local/go/src/trident.li/pitchfork/ui/root.go:133 +0x6b3
trident.li/pitchfork/ui.(PfRootUI).H_root-fm(0x199d840, 0xc420414000, 0xc420459800)
	/usr/local/go/src/trident.li/pitchfork/cmd/server/server.go:118 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc420457180, 0x199d840, 0xc420414000, 0xc420459800)
	/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0x19e5ac0, 0x199d840, 0xc420414000, 0xc420459800)
	/usr/local/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4205969c0, 0x199d840, 0xc420414000, 0xc420459800)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420170000, 0x199e0c0, 0xc42045fa40)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
2018/05/12 16:38:05 /usr/local/go/src/trident.li/pitchfork/lib/db.go:738 DB.exec(UPDATE member_email SET member = $1 WHERE member = $2) error: pq: duplicate key value violates unique constraint "member_trustgroup_pkey"
